### ISSUE TITLE
gdb_bootloader: Reset P1.3 to avoid erratic pin drive in app code

### ISSUE THREAD

**Issue by xparq** [RickKimball/fabooh#2]
As you correctly noted it in a comment yourself ("TODO: probably should reset clock and P1.3 button), please definitely do the button part, because that subtle inconsistency can have serious consequences that may easily remain unnoticed.

Just disable the pullup; P1REN = 0 would do fine.

(As I can see now with a scope, switching the port bit to output _will leave the pull-up enabled_, so the pin cannot reliably be driven low (if at all).
It won't cause problems on the Launchpad, but it rendered my setup unusable: P1.3 is output here, switching another module off when LOW, but was failing while the bootloader was sitting in the flash.)

**Comment by RickKimball** [comment]
You should probably change the code if it conflicts with your use.

**Comment by xparq** [comment]
Nice to see you did the right thing eventually. Now the issue label "wontfix" is misleading though.
